server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics 
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name:usermicroservices}
spring:
  application:
    name: User Service
  datasource:
    url: jdbc:sqlserver://192.168.103.43:52284;databaseName=SmartInventoryDB;TrustServerCertificate=True
    username: ashah
    password: Abhi123@.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
security:
  jwt:
    secret-key: 3cfa76ef14937c1c1EA819f4fc057A80fcd05a7420f8e84cd0a7567c212e005b
    expiration: 3600000
