# docker-compose.yml
services:
  app:
    image: usermicroservice:latest
    ports: ["8080:8091"]
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}     # dev or staging
      SPRING_CONFIG_ADDITIONAL_LOCATION: "file:/config/"
    volumes:
      - ./config/${PROFILE}/:/config:ro
